#!/bin/bash


ipt='/sbin/iptables'
# limpio reglas 

printf '%b\n' '\033[32mFLUSH!\033[39m'
$ipt -F
$ipt -t nat -F
printf '%b\n' '\033[32mPOLITICA GRAL. CERRAMOS TODO. DEJAMOS ENTRAR y SALIR LO SOLICITADO\033[39m'
$ipt -P INPUT DROP
$ipt -P OUTPUT ACCEPT
$ipt -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
$ipt -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# filtro todos los puertos hasta el 10240
printf '%b\n' '\033[32mDROP!\033[39m'
#$ipt -A INPUT -p tcp --dport 21 -j REJECT
#$ipt -A INPUT -p udp --dport 21 -j REJECT
#$ipt -A INPUT -p tcp --dport 23 -j REJECT
#$ipt -A INPUT -p udp --dport 23 -j REJECT
#$ipt -A INPUT -p tcp --dport 25 -j REJECT
#$ipt -A INPUT -p udp --dport 25 -j REJECT
#$ipt -A INPUT -p tcp --dport 81 -j REJECT
#$ipt -A INPUT -p udp --dport 81 -j REJECT
#$ipt -A INPUT -p tcp --dport 111 -j REJECT
#$ipt -A INPUT -p udp --dport 111 -j REJECT
#$ipt -A INPUT -p tcp --dport 179 -j REJECT
#$ipt -A INPUT -p udp --dport 179 -j REJECT
#$ipt -A INPUT -p tcp --dport 554 -j REJECT
#$ipt -A INPUT -p udp --dport 554 -j REJECT
#$ipt -A INPUT -p tcp --dport 1720 -j REJECT
#$ipt -A INPUT -p udp --dport 1720 -j REJECT
#$ipt -A INPUT -p tcp --dport 1755 -j REJECT
#$ipt -A INPUT -p udp --dport 1755 -j REJECT
#$ipt -A INPUT -p tcp --dport 1194 -j REJECT
#$ipt -A INPUT -p udp --dport 1194 -j REJECT
#$ipt -A INPUT -p tcp --dport 5389 -j REJECT
#$ipt -A INPUT -p udp --dport 5389 -j REJECT
#$ipt -A INPUT -p tcp --dport 8080 -j REJECT
#$ipt -A INPUT -p udp --dport 8080 -j REJECT
#$ipt -A INPUT -p tcp --dport 1:10240 -j DROP
#$ipt -A INPUT -p udp --dport 1:10240 -j DROP


printf '%b\n' '\033[32mPROTECCIONES!\033[39m'
#echo "FUCK PING & SMURF ATTACK"
#$ipt -A INPUT -p icmp -i eth1 -j LOG -m limit --log-prefix "iptables ping: "
#echo "1" > /proc/sys/net/ipv4/icmp_echo_ignore_all

printf '%b\n' '\033[32mFUCK BROADCAST & SMURF ATTACK!\033[39m'
echo "1" > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

printf '%b\n' '\033[32mFUCK SPOOFING!\033[39m'
# Para evitar el spoofing nos aseguramos de que la dirección
# origen del paquete viene del sitio correcto."
for interface in /proc/sys/net/ipv4/conf/*/rp_filter; do
	echo "1" > ${interface}
done

# Los ICMPs redirigidos que pueden alterar la tabla de rutas.
for interface in /proc/sys/net/ipv4/conf/*/accept_redirects; do
	echo "0" > ${interface}
done

# No guardamos registros de los marcianos
echo "0" > /proc/sys/net/ipv4/conf/all/log_martians

printf '%b\n' '\033[32mFUCK CHICOS PILLOS y NMAP!\033[39m'
$ipt -A INPUT -m recent --rcheck --seconds 60 -m limit --limit 10/second -j LOG --log-prefix "iptables Pillos "
$ipt -A INPUT -m recent --update --seconds 60 -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags ACK,FIN FIN -j LOG --log-prefix "iptables FIN: "
$ipt -t filter -A INPUT -p tcp --tcp-flags ACK,FIN FIN -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags ACK,PSH PSH -j LOG --log-prefix "iptables PSH: "
$ipt -t filter -A INPUT -p tcp --tcp-flags ACK,PSH PSH -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags ACK,URG URG -j LOG --log-prefix "iptables URG: "
$ipt -t filter -A INPUT -p tcp --tcp-flags ACK,URG URG -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL ALL -j LOG --log-prefix "iptables XMAS scan: "
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL ALL -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL NONE -j LOG --log-prefix "iptables NULL scan: "
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL NONE -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j LOG --log-prefix "iptables pscan: "
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags SYN,FIN SYN,FIN -j LOG --log-prefix "iptables pscan 2: "
$ipt -t filter -A INPUT -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags FIN,RST FIN,RST -j LOG --log-prefix "iptables pscan 2: "
$ipt -t filter -A INPUT -p tcp --tcp-flags FIN,RST FIN,RST -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL SYN,FIN -j LOG --log-prefix "iptables SYNFIN-SCAN: "
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL SYN,FIN -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL URG,PSH,FIN -j LOG --log-prefix "iptables NMAP-XMAS-SCAN: "
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL URG,PSH,FIN -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL FIN -j LOG --log-prefix "iptables FIN-SCAN: "
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL FIN -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL URG,PSH,SYN,FIN -j LOG --log-prefix "iptables NMAP-ID: "
$ipt -t filter -A INPUT -p tcp --tcp-flags ALL URG,PSH,SYN,FIN -j DROP
$ipt -t filter -A INPUT -p tcp --tcp-flags SYN,RST SYN,RST -j LOG --log-prefix "iptables SYN-RST: "
# Drop all null packets
$ipt -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

printf '%b\n' '\033[32mLOCALHOST OK!\033[39m'
$ipt -A INPUT -i lo -j ACCEPT

$ipt -I INPUT -i eth0 -p icmp --icmp-type 8 -j ACCEPT
$ipt -I INPUT -i eth1 -p icmp --icmp-type 8 -j ACCEPT

## Permitimos que la maquina pueda salir a la web
## $ipt -A INPUT -p tcp -m tcp --sport 80 -m state --state RELATED,ESTABLISHED -j ACCEPT
## $ipt -A OUTPUT -p tcp -m tcp --dport 80 -j ACCEPT

printf '%b\n' '\033[32mHABILITAMOS RANGO DE PUERTOS!\033[39m'
# habilito acceso
# $ipt -I INPUT -s 192.168.0.0/16 -j ACCEPT

# habilito mailserver
$ipt -I INPUT -p tcp --dport 22  -j ACCEPT
$ipt -I INPUT -p udp --dport 22  -j ACCEPT
$ipt -I INPUT -p tcp --dport 25  -j ACCEPT
$ipt -I INPUT -p udp --dport 25  -j ACCEPT
$ipt -I INPUT -p tcp --dport 80 -j ACCEPT
$ipt -I INPUT -p udp --dport 80 -j ACCEPT
$ipt -I INPUT -p tcp --dport 110 -j ACCEPT
$ipt -I INPUT -p udp --dport 110 -j ACCEPT
$ipt -I INPUT -p tcp --dport 111 -j ACCEPT
$ipt -I INPUT -p udp --dport 111 -j ACCEPT
$ipt -I INPUT -p tcp --dport 143 -j ACCEPT
$ipt -I INPUT -p udp --dport 143 -j ACCEPT
$ipt -I INPUT -p tcp --dport 389 -j ACCEPT
$ipt -I INPUT -p udp --dport 389 -j ACCEPT
$ipt -I INPUT -p tcp --dport 443 -j ACCEPT
$ipt -I INPUT -p udp --dport 443 -j ACCEPT
$ipt -I INPUT -p tcp --dport 465 -j ACCEPT
$ipt -I INPUT -p udp --dport 465 -j ACCEPT
$ipt -I INPUT -p tcp --dport 587 -j ACCEPT
$ipt -I INPUT -p udp --dport 587 -j ACCEPT
$ipt -I INPUT -p tcp --dport 993 -j ACCEPT
$ipt -I INPUT -p udp --dport 993 -j ACCEPT
$ipt -I INPUT -p tcp --dport 995 -j ACCEPT
$ipt -I INPUT -p udp --dport 995 -j ACCEPT
$ipt -I INPUT -p tcp --dport 5222 -j ACCEPT
$ipt -I INPUT -p udp --dport 5222 -j ACCEPT
$ipt -I INPUT -p tcp --dport 5666 -j ACCEPT
$ipt -I INPUT -p udp --dport 5666 -j ACCEPT
$ipt -I INPUT -p tcp --dport 7025 -j ACCEPT
$ipt -I INPUT -p udp --dport 7025 -j ACCEPT
$ipt -I INPUT -p tcp --dport 7071 -j ACCEPT
$ipt -I INPUT -p udp --dport 7071 -j ACCEPT
$ipt -I INPUT -p tcp --dport 8443 -j ACCEPT
$ipt -I INPUT -p udp --dport 8443 -j ACCEPT
$ipt -I INPUT -p tcp --dport 10024 -j ACCEPT
$ipt -I INPUT -p udp --dport 10024 -j ACCEPT
$ipt -I INPUT -p tcp --dport 10025 -j ACCEPT
$ipt -I INPUT -p udp --dport 10025 -j ACCEPT
$ipt -I INPUT -p tcp --dport 10050  -j ACCEPT
$ipt -I INPUT -p udp --dport 10050  -j ACCEPT

#$ipt -I INPUT -i eth1 -p tcp --dport 443 -j ACCEPT
#$ipt -I INPUT -i eth1 -p udp --dport 443 -j ACCEPT

# habilito dns
#$ipt -I INPUT -p tcp --dport 53 -j ACCEPT
#$ipt -I INPUT -p udp --dport 53 -j ACCEPT
#$ipt -I INPUT -p tcp --dport 953 -j ACCEPT
#$ipt -I INPUT -p udp --dport 953 -j ACCEPT

# HABILITO SALIDA A INTERNET
#echo "POSTROUTING"
#$ipt -t nat -A POSTROUTING --out-interface eth0 -j MASQUERADE
#$ipt -t nat -I POSTROUTING -s 172.100.1.0/24 -d 192.168.1.18 -j MASQUERADE
#$ipt -t nat -I POSTROUTING -s 192.168.0.0/16 -j MASQUERADE 

#$ipt --table nat --append POSTROUTING --out-interface eth1 -j MASQUERADE
#$ipt --append FORWARD --in-interface eth0 -j ACCEPT

# Para habilitar log
#$ipt -A INPUT -j LOG --log-prefix "iptables-input"
#$ipt -A OUTPUT -j LOG --log-prefix "iptables-output"
#$ipt -A FORWARD -j LOG --log-prefix "iptables-forward"

ipsetfw=`ipset list | grep Name | wc -l`
if test $ipsetfw = "0" ; then

BLOCKDB="block.txt"
WORKDIR="/tmp"
pwd=$(pwd)
cd $WORKDIR
#List of ips to block
ipset --create blackips iphash
## Obtain List of badguys from openbl.org
wget -q -c --output-document=$BLOCKDB http://www.openbl.org/lists/base.txt
if [ -f $BLOCKDB ]; then
    IPList=$(grep -Ev "^#" $BLOCKDB | sort -u)
    for i in $IPList
    do
        ipset --add blackips $i
    done
fi
rm $BLOCKDB
## Obtain List of badguys from ciarmy.com
wget -q -c --output-document=$BLOCKDB http://www.ciarmy.com/list/ci-badguys.txt
if [ -f $BLOCKDB ]; then
    IPList=$(grep -Ev "^#" $BLOCKDB | sort -u)
    for i in $IPList
    do
        ipset --add blackips $i
    done
fi
rm $BLOCKDB
## Obtain List of badguys from dshield.org
wget -q -c --output-document=$BLOCKDB http://feeds.dshield.org/top10-2.txt
if [ -f $BLOCKDB ]; then
    IPList=$(grep -E "^[1-9]" $BLOCKDB | cut -f1 | sort -u)
    for i in $IPList
    do
        ipset --add blackips $i
    done
fi
rm $BLOCKDB
#List of networks to block
ipset --create blacknets nethash
## Obtain List of badguys from dshield.org
wget -q -c --output-document=$BLOCKDB http://feeds.dshield.org/block.txt
if [ -f $BLOCKDB ]; then
    IPList=$(grep -E "^[1-9]" $BLOCKDB | cut -f1,3 | sed "s/\t/\//g" | sort -u)
    for i in $IPList
    do
        ipset --add blacknets $i
    done
fi
rm $BLOCKDB
## Obtain List of badguys from spamhaus.org
    wget -q -c --output-document=$BLOCKDB http://www.spamhaus.org/drop/drop.lasso
    if [ -f $BLOCKDB ]; then
      IPList=$(grep -E "^[1-9]" $BLOCKDB | cut -d" " -f1 | sort -u)
      for i in $IPList
      do
        ipset --add blacknets $i
      done
    fi
    rm $BLOCKDB
#Drop blacklisted ips
iptables -I INPUT -p tcp -m set --match-set blackips src -j DROP
iptables -I INPUT -p udp -m set --match-set blackips src -j DROP
iptables -I INPUT -p tcp -m set --match-set blacknets src -j DROP
iptables -I INPUT -p udp -m set --match-set blacknets src -j DROP


cd $pwd
printf '%b\n' '\033[32mIPSET OK!\033[39m'

ALLOW="allow.txt"
## Obtener ips de Argentina
    ipset --create argentina nethash
    wget -q -c --output-document=$ALLOW http://www.ipdeny.com/ipblocks/data/countries/ar.zone
	echo "" > ar.zone
    if [ -f $ALLOW ]; then
      IPList=$(grep -E "^[1-9]" $ALLOW | cut -d" " -f1 | sort -u)
      for i in $IPList
      do
        ipset --add argentina $i
      done
    fi
    rm $ALLOW
iptables -I INPUT -p tcp -m set --match-set argentina src -j ACCEPT
iptables -I INPUT -p udp -m set --match-set argentina src -j ACCEPT

printf '%b\n' '\033[32mIPSET ARG OK!\033[39m'
cd $pwd
else
printf '%b\n' '\033[32mIPSET BLOCKS OK!\033[39m'
fi

