#!/bin/bash
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar labad@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar madelardi@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar laguilera@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar gaguirre@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar malcoba@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lalfaro@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ealfonso@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lalfonzo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar dalmaraz@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar salonso@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar nalvarez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jalvarez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar aanderson@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mandia@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar napellido@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar marancibia@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar aarriola@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar fasseff@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar abaldo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pbalduzzi@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pbasalo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mbasso@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar nbauni@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar dbecchetti@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar rbello@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar nbento@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar yberlato@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mblanco@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ebolert@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar nborri@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar gbotte@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mbruce@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar sbulacios@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar abustamante@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jcabral@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mcabrera@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mcalero@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ecaputo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pcarrasco@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar fcarratu@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ncastillo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mcatania@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ccayzac@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pcervellini@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar dcipolat@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pcolazo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mcordoba@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar acorvalan@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar gcotti@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ldaquino@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mdemarco@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar sdeusubiaga@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pdelcastello@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar gdelprete@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar fdevoto@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pdiaz@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mdiaz@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar aparodi@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ldobruskin@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ddomine@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar fdominguez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ldottavio@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar vdure@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar bdaurelio@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar peckhardt@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar vespejo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mesposito@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lfabbro@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ffabio@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar gfajn@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mfarias@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar dfernandez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mfernandez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lfernandez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar nfidalgo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lflores@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lformica@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar gfranco@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lnfranco@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar gfuentes@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jfunari@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar cgadea@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar vgalvagno@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ggambero@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mgarcia@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar dgarcia@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jglopez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar rlgarcia@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar bghigliano@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ggibert@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar cgimenez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pgimenez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar rgimenez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ggiovio@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pgirotti@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ncgomez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ygomez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ngomez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mgomez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pgonzalez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar egraci@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pguendulain@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jguerberoff@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jguerberoff@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar blynch@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar dguille@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ahernandez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jibalo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jibarra@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar siorio@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar aiuri@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mizaguirre@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar cjordan@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ajungblut@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mkobelt@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar alarocca@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pleanza@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar aledesma@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar eleguizamon@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mlemos@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar flemos@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jlequio@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jlombardi@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar plopez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar flopez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar aslopez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jflopez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jflopez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar llukaszyk@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar smaggiolo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar rmarcos@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mmarinoni@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar eemartinez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar gmartini@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lmartini@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar dmartini@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar smateo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ameana@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar gmendez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mmendiguren@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar amenon@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar gmerani@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lmichavila@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar smolina@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jmontoya@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mmorales@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mnicoletti@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar soliva@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar nolmedo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar volmedo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lopen@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar roropeza@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar rosuna@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar adelicado@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lpalmeiro@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mpanero@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mpantaleon@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar sparagliola@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar vpare@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar spastene@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lpasti@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ipenna@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mpenna@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lperrando@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar epodesta@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar spombo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar kprat@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar sprellezo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar aquarleri@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar eramirez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mrizzo@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar aroa@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar arodiz@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mroiffe@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar rrojas@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mroldan@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar iromanuk@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar cromero@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jrossotti@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pruizdiaz@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jsalas@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar rsalgado@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar psalvatore@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar msanesteban@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar lsanchez@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar cschejter@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jschuster@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar esebastiano@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar asenyk@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar dserralta@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar asforza@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar fsinagra@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar nslatman@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar nsolla@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar dsoria@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar dstella@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jsutil@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar wszelagowski@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar rtibaldi@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar rtorales@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar etorrens@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar htorres@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ftorres@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar ftoth@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar etricarico@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar bufor@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar aurtubey@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar nvacas@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar jvalenzuela@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar bvargas@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mwainfeld@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar azamora@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar pzapata@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar mzavalia@renatea.gob.ar
/opt/zimbra/bin/zmprov adlm central@renatea.gob.ar nzetzsche@renatea.gob.ar
