#!/bin/bash
echo -ne "\nSOFTWARE ZIMBRA\n"
echo "-------------------------------------"
echo -ne "\nZimbra:\n"
su - zimbra -c "/opt/zimbra/bin/zmcontrol -v"
echo -ne "\n\nSOFTWARE DE FILTRADO DE CORREO\n"
echo "-------------------------------------"
echo -ne "\nPostfix:\n"
su - zimbra -c "postconf -d | grep 'mail_version ='"
echo -ne "\nAmavis:\n"
su - zimbra -c "/opt/zimbra/amavisd/sbin/amavisd -V"
echo -ne "\nClamAV:\n"
su - zimbra -c "/opt/zimbra/clamav/bin/clamscan -V"
echo -ne "\nSpamassassin:\n"
su - zimbra -c "/opt/zimbra/libexec/sa-learn -V"
echo -ne "\nDspam:\n"
su - zimbra -c "/opt/zimbra/dspam/bin/dspam --version | head -2"
echo -ne "\nSOFTWARE WEB\n"
echo "-------------------------------------"
echo -ne "\nApache:\n"
su - zimbra -c "/opt/zimbra/httpd/bin/httpd -v"
echo -ne "\nJava:\n"
su - zimbra -c "/opt/zimbra/java/bin/java -version"
echo -ne "\nOpenSSL:\n"
su - zimbra -c "/opt/zimbra/openssl/bin/openssl version"
echo -ne "\n\nSOFTWARE BASES DE DATOS\n"
echo "-------------------------------------"
echo -ne "\nOpenLDAP:\n"
su - zimbra -c "/opt/zimbra/openldap/sbin/slapd -V"
echo -ne "\nMySQL:\n"
su - zimbra -c "/opt/zimbra/mysql/bin/mysql -V"
echo -ne "\n\nOTRO SOFTWARE\n"
echo "-------------------------------------"
echo -ne "\nOpenDKIM:\n"
su - zimbra -c "/opt/zimbra/opendkim/sbin/opendkim -V | head -2"
echo -ne "\nAltermime:\n"
su - zimbra -c "/opt/zimbra/altermime/bin/altermime --version"
echo -ne "\nAspell:\n"
su - zimbra -c "/opt/zimbra/aspell/bin/aspell -v"
echo -ne "\nCurl:\n"
su - zimbra -c "/opt/zimbra/curl/bin/curl -V | head -1"
echo -ne "\nCyrus-SASL:\n"
su - zimbra -c "/opt/zimbra/cyrus-sasl/sbin/saslauthd -v"
